/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedtickedsTickedsRouteImport } from './routes/_protected/(tickeds)/tickeds'
import { Route as ProtectedprojectsProjectsRouteImport } from './routes/_protected/(projects)/projects'
import { Route as ProtectedinvoicesInvoicesRouteImport } from './routes/_protected/(invoices)/invoices'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedtickedsTickedsRoute = ProtectedtickedsTickedsRouteImport.update({
  id: '/(tickeds)/tickeds',
  path: '/tickeds',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedprojectsProjectsRoute =
  ProtectedprojectsProjectsRouteImport.update({
    id: '/(projects)/projects',
    path: '/projects',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedinvoicesInvoicesRoute =
  ProtectedinvoicesInvoicesRouteImport.update({
    id: '/(invoices)/invoices',
    path: '/invoices',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/invoices': typeof ProtectedinvoicesInvoicesRoute
  '/projects': typeof ProtectedprojectsProjectsRoute
  '/tickeds': typeof ProtectedtickedsTickedsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/': typeof ProtectedIndexRoute
  '/invoices': typeof ProtectedinvoicesInvoicesRoute
  '/projects': typeof ProtectedprojectsProjectsRoute
  '/tickeds': typeof ProtectedtickedsTickedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/register': typeof RegisterRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/(invoices)/invoices': typeof ProtectedinvoicesInvoicesRoute
  '/_protected/(projects)/projects': typeof ProtectedprojectsProjectsRoute
  '/_protected/(tickeds)/tickeds': typeof ProtectedtickedsTickedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/otp'
    | '/register'
    | '/invoices'
    | '/projects'
    | '/tickeds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/otp'
    | '/register'
    | '/'
    | '/invoices'
    | '/projects'
    | '/tickeds'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/otp'
    | '/register'
    | '/_protected/'
    | '/_protected/(invoices)/invoices'
    | '/_protected/(projects)/projects'
    | '/_protected/(tickeds)/tickeds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(tickeds)/tickeds': {
      id: '/_protected/(tickeds)/tickeds'
      path: '/tickeds'
      fullPath: '/tickeds'
      preLoaderRoute: typeof ProtectedtickedsTickedsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(projects)/projects': {
      id: '/_protected/(projects)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedprojectsProjectsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(invoices)/invoices': {
      id: '/_protected/(invoices)/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof ProtectedinvoicesInvoicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedinvoicesInvoicesRoute: typeof ProtectedinvoicesInvoicesRoute
  ProtectedprojectsProjectsRoute: typeof ProtectedprojectsProjectsRoute
  ProtectedtickedsTickedsRoute: typeof ProtectedtickedsTickedsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedinvoicesInvoicesRoute: ProtectedinvoicesInvoicesRoute,
  ProtectedprojectsProjectsRoute: ProtectedprojectsProjectsRoute,
  ProtectedtickedsTickedsRoute: ProtectedtickedsTickedsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
