/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as tickedsTickedsRouteImport } from './routes/(tickeds)/tickeds'
import { Route as projectsProjectsRouteImport } from './routes/(projects)/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const tickedsTickedsRoute = tickedsTickedsRouteImport.update({
  id: '/(tickeds)/tickeds',
  path: '/tickeds',
  getParentRoute: () => rootRouteImport,
} as any)
const projectsProjectsRoute = projectsProjectsRouteImport.update({
  id: '/(projects)/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof projectsProjectsRoute
  '/tickeds': typeof tickedsTickedsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof projectsProjectsRoute
  '/tickeds': typeof tickedsTickedsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(projects)/projects': typeof projectsProjectsRoute
  '/(tickeds)/tickeds': typeof tickedsTickedsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/tickeds'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/tickeds'
  id: '__root__' | '/' | '/(projects)/projects' | '/(tickeds)/tickeds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  projectsProjectsRoute: typeof projectsProjectsRoute
  tickedsTickedsRoute: typeof tickedsTickedsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(tickeds)/tickeds': {
      id: '/(tickeds)/tickeds'
      path: '/tickeds'
      fullPath: '/tickeds'
      preLoaderRoute: typeof tickedsTickedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(projects)/projects': {
      id: '/(projects)/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof projectsProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  projectsProjectsRoute: projectsProjectsRoute,
  tickedsTickedsRoute: tickedsTickedsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
